Add workshop archive page
uclaacm/hack.uclaacm.com pull request #101
Opened 2020-09-13 04:59 UTC by jodymlin

2020-09-20 02:17 UTC, GalenWong requested changes

2020-09-20 02:17 UTC, GalenWong commented on src/components/ArchivePage/ArchivePageTemplate.js
> +	const secondEventYear = secondEventDate.split(' ')[1];
```suggestion
	const [firstEventQuarter, firstEventYear] = firstEventDate.split(' ');
	const [secondEventQuarter, secondEventYear] = secondEventDate.split(' ');
```

2020-09-20 02:17 UTC, GalenWong commented on src/components/ArchivePage/WorkshopInfoItem.js
> +		<Link href={link} {...props} >{text}&nbsp;</Link>
use ``{` `}`` instead of `&nbsp`. Just put any special character in quotes so we don't have to look up the encoding.

2020-09-20 04:01 UTC, GalenWong approved these changes

2020-09-20 04:05 UTC, merged

2020-09-22 05:38 UTC, TimothyGu commented
This looks seriously awesome. Great work @jodymlin!

2020-09-22 05:39 UTC, TimothyGu commented on src/components/ArchivePage/WorkshopInfoItem.js
> +		&nbsp; {/* HTML code for space */}
nbsp is not space; it's a [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space), which prevents line breaks at this particular location. You may wish to check if this is the intended effect.

2020-09-22 05:40 UTC, TimothyGu commented on src/components/ArchivePage/WorkshopInfoItem.js
> +			}
nit: for future I believe you could do

```js
{repo && <LinkItem link={repo} text='README' />}
```

looks a bit cleaner than the conditional operator.

2020-09-22 05:41 UTC, TimothyGu commented on src/data/events/archive/fall2019/javascript-chats.yml
> +- name: Javascript Chats
nit: #106