initial commit, changed banner
uclaacm/hack.uclaacm.com pull request #111
Opened 2020-10-01 03:32 UTC by khxia

#103 Actually, not sure if changing to banner in the Homepage falls under #103.

2020-10-01 06:31 UTC, jodymlin reviewed
**A few SVG things**:
![image](https://user-images.githubusercontent.com/44387428/94774601-11d18c00-0373-11eb-9885-d6558607785a.png)
* some weird shadows under that get chopped off and look funny. 2 things we can do here, either make the svg height reach all the way to the bottom of the banner, or (need ur advice @GalenWong) remove the shadows.


![image](https://user-images.githubusercontent.com/44387428/94774819-78ef4080-0373-11eb-8ef4-e84313cb2f8e.png)
* the google home/alexa i think is missing part of the wiring/plug. Perhaps got deleted when trying to export it. The top of the wiring also doesn't go to the top of the banner and gets cutoff early. 


* The SVG on the right also seems a little bigger than the one on the left. I noticed because the code blocks on the right look bigger the code blocks on the left. Not sure if it just turned out this way when the SVGs were exported. If it's too hard to fix, we can always try fix it later. 


**Stuff with Banner cutoff**:
Earlier we discussed ways to fix the awkward code block cutoffs on the. I have an idea (@GalenWong need your design wisdom): What if we edited the SVG code blocks in the background so that they all end before getting cutoff. Then we re-export the SVG and use that. 

**ACM Hack Wordmark**
Design recreated the wordmarks so that there shouldn't be issues rendering them. The working versions should be in the ACM at UCLA drive. We can probably use this wordmark to fix the banner.

2020-10-01 07:17 UTC, khxia commented
> **A few SVG things**:
> ![image](https://user-images.githubusercontent.com/44387428/94774601-11d18c00-0373-11eb-9885-d6558607785a.png)
> 
> * some weird shadows under that get chopped off and look funny. 2 things we can do here, either make the svg height reach all the way to the bottom of the banner, or (need ur advice @GalenWong) remove the shadows.
> 
> ![image](https://user-images.githubusercontent.com/44387428/94774819-78ef4080-0373-11eb-8ef4-e84313cb2f8e.png)
> 
> * the google home/alexa i think is missing part of the wiring/plug. Perhaps got deleted when trying to export it. The top of the wiring also doesn't go to the top of the banner and gets cutoff early.
> * The SVG on the right also seems a little bigger than the one on the left. I noticed because the code blocks on the right look bigger the code blocks on the left. Not sure if it just turned out this way when the SVGs were exported. If it's too hard to fix, we can always try fix it later.
> 
> **Stuff with Banner cutoff**:
> Earlier we discussed ways to fix the awkward code block cutoffs on the. I have an idea (@GalenWong need your design wisdom): What if we edited the SVG code blocks in the background so that they all end before getting cutoff. Then we re-export the SVG and use that.
> 
> **ACM Hack Wordmark**
> Design recreated the wordmarks so that there shouldn't be issues rendering them. The working versions should be in the ACM at UCLA drive. We can probably use this wordmark to fix the banner.

2020-10-01 07:28 UTC, khxia commented
Fixed most of the issues. 

Except:
- For me, the ACM Hack Wordmark still doesn't work even with the new svg on the UCLA at ACM drive. Now, instead of showing a pink block, the "hack" doesn't even render at all
- For the banner cutoff idea, I already did what @jodymlin suggested regarding the cutoffs for code blocks on the top and bottom. (I think that code block cutoffs horizontally are part of the design, unless I'm wrong)

2020-10-01 09:21 UTC, GalenWong commented
> * For me, the ACM Hack Wordmark still doesn't work even with the new svg on the UCLA at ACM drive. Now, instead of showing a pink block, the "hack" doesn't even render at all

I will take a look. It might take some rework of the logo.

2020-10-01 13:25 UTC, GalenWong commented
@khxia i uploaded another logo that should work in the browser in the drive. try again.

2020-10-01 13:28 UTC, GalenWong commented
> For the banner cutoff idea, I already did what @jodymlin suggested regarding the cutoffs for code blocks on the top and bottom. (I think that code block cutoffs horizontally are part of the design, unless I'm wrong)

We don't want the horizontal cut of (at least I don't). We can just let the long code blocks overflow out horizontally. And I actually don't mind the SVG for the IDE to overflow out a bit as well. Let me know if you need SVG assets.

2020-10-04 03:44 UTC, GalenWong requested changes

2020-10-04 03:44 UTC, GalenWong commented on src/components/HomePage/Banner.js
> +			width={500} height={800} />
```suggestion
		<SvgImg
		  imgStyle={{ width: 'auto' }}
		  className={classes.rightBanner}
		  src={leftbanner}
			width={500}
			height={800}
		/>
```

2020-10-04 03:44 UTC, GalenWong commented on src/components/HomePage/Banner.js
> +			width={500} height={800} />
```suggestion
		<SvgImg 
		  imgStyle={{ width: 'auto' }}
		  className={classes.leftBanner}
		  src={rightbanner}
			width={500}
			height={800}
		/>
```

2020-10-04 03:44 UTC, GalenWong commented on src/components/HomePage/Banner.js
> +		<SvgImg className={classes.wordmark} src={wordmark} width={1300} height={272.9} />
add a comment here to explain why the hardcoded width and height

2020-10-04 04:10 UTC, GalenWong approved these changes

2020-10-04 04:11 UTC, merged