updated font, logo, wordmark, and colors
uclaacm/hack.uclaacm.com pull request #113
Opened 2020-10-01 23:16 UTC by jodymlin

* Updated font and font family
  * Display/Header font: Poppins
  * Body: Open Sans
* Updated new colors where applicable (not all of our palette has new colors, but we also never use some of our palette anyway)
* switched to new logo and wordmark
* Componentized the page headers 
* Change some typography variants on some pages to look nicer with the new font family update

2020-10-03 07:02 UTC, TimothyGu commented on src/components/HeadFooter/HeadFooter.js
> +			light: '#f05b84', // did not receive updates for this color
The comment won't make sense after a year. To convey some information to the reviewer, you can instead comment on your own PRs.

2020-10-03 07:02 UTC, TimothyGu commented on src/components/PageTitle/PageTitle.js
> +
remove the empty new lines please. surprised ESLint didn't catch this.

2020-10-04 02:41 UTC, khxia reviewed
There's some empty lines here

2020-10-04 03:16 UTC, GalenWong requested changes
- Change the blog post cards on the homepage to use OpenSans
- The title weight on the markdown pages (blogs) is now invalid. We should either import opensans with those weights or we update our weight number, or we should just use poppins
- maybe we should use 600/700 for title poppins font weights
- remove `font-weight: lighter` on team page officer descriptions

2020-10-04 04:03 UTC, GalenWong requested changes

2020-10-04 04:03 UTC, GalenWong commented on src/components/HeadFooter/HeadFooter.js
> +		h1: { fontFamily: '"Poppins", sans-serif', fontWeight: '600' },
```suggestion
		h1: { fontFamily: '"Poppins", sans-serif', fontWeight: '600' },
		h2: { fontFamily: '"Poppins", sans-serif', fontWeight: '600' },
```

2020-10-04 04:19 UTC, GalenWong approved these changes

2020-10-04 07:18 UTC, merged