Linking to an expanded workshop archive
uclaacm/hack.uclaacm.com pull request #312
Opened 2022-05-01 05:13 UTC by katelynsyu

# Changes

- add ID to all accordions, so that adding quarter-year-eventName to the archive url will take you to the relevant accordion
- add a button that will copy the link to the accordion
- when linked to the accordion, the accordion will load as expanded

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Related Issues

Fixes #167

2022-05-21 18:41 UTC, katelynsyu commented
to do:
- [ ] ensure that clicking the link icon doesn't open the accordion
- [ ] if the url is to a valid accordion, set isExpanded to true and render it expanded.

2022-07-07 04:04 UTC, khxia requested changes
Our build is failing rip

2022-07-07 04:04 UTC, khxia commented on src/components/ArchivePage/EventInfoItem.js
> +	console.log(`window: `, window.location.hash)
looks like this line is causing our build to fail. Try to remove it and see if running `yarn build` works.

2022-07-07 04:04 UTC, khxia commented on src/components/ArchivePage/EventInfoItem.js
> +	const [hash, setHash] = useState(window.location.hash);
I actually think generally we aren't able to use the `window` object in the function body except in a react useEffect. https://blog.greenroots.info/gatsby-the-window-is-not-defined-error-what-and-how-to-fix-it 

Could you try play around with it and see what works in yarn build?

2022-07-17 18:17 UTC, khxia requested changes

2022-07-17 18:17 UTC, khxia commented on src/components/ArchivePage/ArchivePageTemplate.js
> +					// name = quarter + " " + event.name
get rid of these comments

2022-07-24 03:50 UTC, khxia approved these changes
Looks good to me!

2022-07-24 03:50 UTC, merged