Added Winter events
uclaacm/hack.uclaacm.com pull request #430
Opened 2024-01-13 23:41 UTC by jamesmwu

# Changes

Updated event descriptions.
Fixes #424 

## Type of change

Please delete options that are not relevant.

- [X] Content Update (non-breaking change which updates the content of the website)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2024-01-14 18:29 UTC, katelynsyu requested changes
You also need to add event dates in src/data/events.js, like when the indiv stackschool workshops are, etc

2024-01-16 20:04 UTC, jamesmwu commented
Note:
Still missing assets for HOTH, location for HOTH TBA.

Abbreviated / shortened some of the Stackschool workshop names to prevent text overlapping the Details button of the card component-- I'm assuming it's intentional that the card component dimensions are hard-coded so height doesn't increase.

2024-01-17 00:34 UTC, katelynsyu requested changes

2024-01-17 00:34 UTC, katelynsyu commented on src/data/events.js
> +		date: getDateTime(2024, 3, 7, 18),
Stackschool #7 is in Week 8 which should be 2/29

2024-01-17 00:34 UTC, katelynsyu commented on src/data/events.js
> +		date: getDateTime(2024, 3, 14, 18),
Should be 3/7/24

2024-01-17 00:34 UTC, katelynsyu commented on src/data/events.js
> +		detailLink: 'https://discord.gg/rup2p6fxA5'
detailLink should be hoth website [hoth.uclaacm.com](https://hoth.uclaacm.com)

2024-01-17 00:34 UTC, katelynsyu commented on src/data/events.js
> +		name: 'Hack On The Hill XII',
We're on HOTH XI not XII

2024-01-17 00:34 UTC, katelynsyu commented on src/data/events.js
> +	{
Can we get rid of all of last quarter's events pls?

2024-01-17 00:42 UTC, jamesmwu commented
This is what I get for using copilot

2024-01-17 01:09 UTC, katelynsyu approved these changes
lgtm. boo copilot

2024-01-17 01:09 UTC, merged