added HOTH banner, changed HOTH button to website
uclaacm/hack.uclaacm.com pull request #435
Opened 2024-02-05 00:52 UTC by lilliangonick

# Changes
Changed the HOTH XI button to link to the hoth website instead of discord. Added the new HOTH XI banner to the highlights and event page. 

## Type of change
- [ ] Content Update (non-breaking change which updates the content of the website)

# Related Issues
close #431

2024-02-05 01:01 UTC, nathanzzhang approved these changes
LGTM!!!!! Nice work!

2024-02-05 19:17 UTC, katelynsyu requested changes

2024-02-15 23:07 UTC, katelynsyu requested changes

2024-02-15 23:07 UTC, katelynsyu commented on src/data/events.js
>  		location: 'Location to be announced!',
Can you change all the locations to `Carnesale Commons, Palisades Room`?

2024-02-15 23:07 UTC, katelynsyu commented on src/images/event/2024w-hoth-XI-banner.png
HOTH finally got a location, so let's replace the banner with the `Facebook_post.png` image here: https://drive.google.com/drive/folders/14kkZ3Hng1YZFmPiBq0Q0iEkR4_w3BGUv

2024-02-15 23:23 UTC, lilliangonick commented on src/images/event/2024w-hoth-XI-banner.png
i just added the changes! i also updated the date to be march 3rd instead of march 2nd.

2024-02-16 00:00 UTC, nathanzzhang commented on src/images/event/2024w-hoth-XI-banner.png
seems like there's a deploy issue. I think it might have to do with the naming of the banner that you added and the naming of the image when you actually import it!

2024-02-16 00:01 UTC, nathanzzhang requested changes
minor change in naming so it deploys!

2024-02-16 00:01 UTC, nathanzzhang commented on src/data/highlights.js
> +		imgFilePath: 'event/2024w-hoth-xi-banner.png',
"xi" should be "XI"!

2024-02-19 21:14 UTC, nathanzzhang requested changes
Minor nit!

2024-02-19 21:14 UTC, nathanzzhang commented on src/components/2024w-hoth-XI-banner.png
Nit: we can actually delete this file now! For future reference, all of our images go in /images/event so they can be found with our Gatsby queries (they don't go in /components).

2024-02-19 21:20 UTC, lilliangonick commented on src/components/2024w-hoth-XI-banner.png
okok sorry that was a mistake i am not sure how that ended up there. i just deleted the file!

2024-02-19 21:22 UTC, nathanzzhang commented on src/components/2024w-hoth-XI-banner.png
LOL all good nwnw!

2024-02-19 21:24 UTC, nathanzzhang approved these changes
lgtm! nice work!

2024-02-19 22:52 UTC, katelynsyu requested changes
Looks like we have a few extra files that got added somehow. If we delete them, this should be good to go!

2024-02-19 22:52 UTC, katelynsyu commented on src/components/events.js
There should be an `events.js` file in the `components` folder. Can we delete this?

2024-02-19 22:52 UTC, katelynsyu commented on src/components/highlights.js
I don't think there's supposed to be a `highlights.js` file in `components` either. Can we delete this?

2024-02-20 01:06 UTC, lilliangonick commented on src/components/highlights.js
got it! im so sorry i have no idea how those got there. thank you! should be all good now!

2024-02-20 01:54 UTC, katelynsyu approved these changes
lgtm!

2024-02-20 01:54 UTC, merged